# Generated by Django 4.2.6 on 2024-09-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='task',
            name='incident',
            field=models.CharField(choices=[('Potrojari', 'Potrojari'), ('Slowness', 'Slowness'), ('Note Pending', 'Note Pending'), ('Synchronize', 'Synchronize'), ('Template', 'Template'), ('Password', 'Password'), ('User Information', 'User Information'), ('OTP', 'OTP'), ('PDF Generation Error', 'PDF Generation Error'), ('Dak Upload', 'Dak Upload'), ('Office/Branch Information Correction', 'Office/Branch Information Correction'), ('Dak Forward', 'Dak Forward'), ('Nothi Permission', 'Nothi Permission'), ('Nothi Information Correction', 'Nothi Information Correction'), ('Archive', 'Archive'), ('Nothi Forward', 'Nothi Forward'), ('Dashboard', 'Dashboard'), ('Heading Correction', 'Heading Correction'), ('Substitute', 'Substitute'), ('Signature', 'Signature'), ('Doptor', 'Doptor'), ('Designation Align', 'Designation Align'), ('User Assign', 'User Assign'), ('User Release', 'User Release'), ('Dak Not Found', 'Dak Not Found'), ('Nothi Not Found', 'Nothi Not Found'), ('PDF Blank', 'PDF Blank'), ('Others', 'Others')], default='Others', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='office_name',
            field=models.CharField(default='Unknown Office', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('Phone Call', 'Phone Call'), ('Personal Email', 'Personal Email'), ('OTRS', 'OTRS'), ('SMS', 'SMS'), ('One 2 One', 'One 2 One'), ('Training', 'Training'), ('i-Top', 'i-Top'), ('AnyDesk', 'AnyDesk'), ('WhatsApp', 'WhatsApp'), ('Soical Platforms', 'Social Platforms'), ('Productivity / Creativity', 'Productivity / Creativity'), ('Team Work', 'Team Work'), ('Personal', 'Personal'), ('Meeting', 'Meeting'), ('Nothi System', 'Nothi System'), ('Self Initiative', 'Self Initiative'), ('Super Admin', 'Super Admin'), ('Others', 'Others'), ('All', 'All')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='support_category',
            field=models.CharField(choices=[('User Management', 'User Management'), ('Organogram Management', 'Organogram Management'), ('Training Management', 'Training Management'), ('Incident Management', 'Incident Management'), ('Knowledge Sharing', 'Knowledge Sharing'), ('System Management', 'System Management'), ('Doc/Exl/Sheet Management', 'Doc/Exl/Sheet Management'), ('Productivity / Creativity', 'Productivity / Creativity'), ('Nothi / Note / File Management', 'Nothi / Note / File Management'), ('Team Management', 'Team Management'), ('Tech / Vendor Management', 'Tech / Vendor Management'), ('Migration Management', 'Migration Management'), ('myGov Management', 'myGov Management'), ('Mobile Application', 'Mobile Application'), ('Implementation', 'Implementation'), ('Query Management', 'Query Management'), ('Reporting', 'Reporting'), ('System Testing', 'System Testing'), ('Capacity Development', 'Capacity Development'), ('Tutorial Management', 'Tutorial Management'), ('Others', 'Others'), ('Office Management', 'Office Management'), ('Logistics / Apparatus Management', 'Logistics / Apparatus Management'), ('Request Management', 'Request Management'), ('All', 'All')], default='Phone Call', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Dependency', 'Dependency'), ('Pending', 'Pending'), ('Done', 'Done'), ('Working', 'Working'), ('i-Top', 'i-Top'), ('Others', 'Others')], max_length=50),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='tasks.task')),
            ],
        ),
    ]
