# Generated by Django 4.2.6 on 2024-09-14 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_attachment_task_incident_task_office_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('Phone Call', 'Phone Call'), ('Personal Email', 'Personal Email'), ('OTRS', 'OTRS'), ('SMS', 'SMS'), ('One 2 One', 'One 2 One'), ('Training', 'Training'), ('i-Top', 'i-Top'), ('AnyDesk', 'AnyDesk'), ('WhatsApp', 'WhatsApp'), ('Social Platforms', 'Social Platforms'), ('Productivity / Creativity', 'Productivity / Creativity'), ('Team Work', 'Team Work'), ('Personal', 'Personal'), ('Meeting', 'Meeting'), ('Nothi System', 'Nothi System'), ('Self Initiative', 'Self Initiative'), ('Super Admin', 'Super Admin'), ('Others', 'Others'), ('All', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task'),
        ),
    ]
