# Generated by Django 4.2.6 on 2024-09-14 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_attachment_alter_task_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='tasks.task'),
        ),
    ]
