# Generated by Django 4.2.6 on 2024-09-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskattachment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='support_category',
            field=models.CharField(choices=[('User Management', 'User Management'), ('Organogram Management', 'Organogram Management'), ('Training Management', 'Training Management'), ('Incident Management', 'Incident Management'), ('Knowledge Sharing', 'Knowledge Sharing'), ('System Management', 'System Management'), ('Doc/Exl/Sheet Management', 'Doc/Exl/Sheet Management'), ('Productivity / Creativity', 'Productivity / Creativity'), ('Nothi / Note / File Management', 'Nothi / Note / File Management'), ('Team Management', 'Team Management'), ('Tech / Vendor Management', 'Tech / Vendor Management'), ('Migration Management', 'Migration Management'), ('myGov Management', 'myGov Management'), ('Mobile Application', 'Mobile Application'), ('Implementation', 'Implementation'), ('Query Management', 'Query Management'), ('Reporting', 'Reporting'), ('System Testing', 'System Testing'), ('Capacity Development', 'Capacity Development'), ('Tutorial Management', 'Tutorial Management'), ('Others', 'Others')], max_length=100),
        ),
    ]
