# Generated by Django 4.2.6 on 2024-09-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_userprofile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('Phone Call', 'Phone Call'), ('Personal Email', 'Personal Email'), ('OTRS', 'OTRS'), ('SMS', 'SMS'), ('One 2 One', 'One 2 One'), ('Training', 'Training'), ('i-Top', 'i-Top'), ('AnyDesk', 'AnyDesk'), ('WhatsApp', 'WhatsApp'), ('Social Platforms', 'Social Platforms'), ('Productivity / Creativity', 'Productivity / Creativity'), ('Team Work', 'Team Work'), ('Personal', 'Personal'), ('Meeting', 'Meeting'), ('Nothi System', 'Nothi System'), ('Self Initiative', 'Self Initiative'), ('Super Admin', 'Super Admin'), ('Others', 'Others')], max_length=100),
        ),
    ]
