# Generated by Django 4.2.6 on 2024-09-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('tasks', '0015_delete_incident_delete_source_delete_supportcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='SupportCategory',
        ),
        migrations.AlterField(
            model_name='task',
            name='incident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.incident'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.source'),
        ),
        migrations.AlterField(
            model_name='task',
            name='support_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.supportcategory'),
        ),
    ]
