# Generated by Django 4.2.6 on 2024-09-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_delete_incident_delete_source_delete_supportcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('general', 'General User'), ('team_coordinator', 'Team Coordinator')], max_length=20),
        ),
    ]
